name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"
  release:
    types: [ published ]

jobs:
  build:
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
      fail-fast: false

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      - name: Get project dependencies
        run: go mod download

      - name: Build XrayR
        run: |
          mkdir -p build_assets
          go build -v -o build_assets/XrayR -trimpath -ldflags "-s -w -buildid="

      - name: Prepare release assets
        run: |
          cp ${GITHUB_WORKSPACE}/README.md ./build_assets/README.md
          cp ${GITHUB_WORKSPACE}/LICENSE ./build_assets/LICENSE
          cp ${GITHUB_WORKSPACE}/release/config/dns.json ./build_assets/dns.json
          cp ${GITHUB_WORKSPACE}/release/config/route.json ./build_assets/route.json
          cp ${GITHUB_WORKSPACE}/release/config/custom_outbound.json ./build_assets/custom_outbound.json
          cp ${GITHUB_WORKSPACE}/release/config/custom_inbound.json ./build_assets/custom_inbound.json
          cp ${GITHUB_WORKSPACE}/release/config/rulelist ./build_assets/rulelist
          cp ${GITHUB_WORKSPACE}/release/config/config.yml.example ./build_assets/config.yml

      - name: Create ZIP archive
        shell: bash
        run: |
          pushd build_assets || exit 1
          zip -9vr ../XrayR-linux-amd64.zip .
          popd || exit 1
          FILE=./XrayR-linux-amd64.zip
          DGST=$FILE.dgst
          for METHOD in md5 sha1 sha256 sha512; do
            openssl dgst -$METHOD $FILE | sed 's/([^)]*)//g' >>$DGST
          done

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: XrayR-linux-amd64
          path: ./XrayR-linux-amd64.zip*

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./XrayR-linux-amd64.zip*
          tag: ${{ github.ref }}
          file_glob: true
